branches:
  only:
    - master
    - develop
os: osx
sudo: false
language: node_js
node_js:
  - "8"
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
- wget http://dl.google.com/android/android-sdk_r24.4.1-macosx.zip
- unzip android-sdk_r24.4.1-macosx.zip
- export M2_HOME=/usr/local/maven
- export ANDROID_HOME=$PWD/android-sdk-macosx
- export ZIPALIGN_HOME=$PWD/android-sdk-macosx/build-tools/23.0.3
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
- echo yes | android update sdk --filter android-23 --no-ui --force > /dev/null
- echo yes | android update sdk --filter build-tools-23.0.3 --all --no-ui --force > /dev/null
- echo yes | android update sdk --filter sysimg-23 --no-ui --force > /dev/null
- echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
- echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null
- wget --no-check-certificate http://apache.website-solution.net//ant/binaries/apache-ant-1.10.3-bin.zip
- tar -xzvf apache-ant-1.10.3-bin.zip
- export ANT_HOME=$PWD/apache-ant-1.10.3
- export PATH=${ANT_HOME}/bin:$PATH

install:
  - echo "$JAVA_HOME"
  - echo "$ANDROID_HOME"
  - echo "$ZIPALIGN_HOME"
  - echo "$M2_HOME"
  - echo "$ANT_HOME"
  - npm install
  - bower install
script:
  - npm run build
